# in directory ~/Repo/blog/sponge
# docker build -f DockerFile -t blog:latest .
# docker run -it --privileged --cpus=8 blog:latest

FROM nginx
WORKDIR /my/site
COPY nginx.conf /etc/nginx/nginx.conf



