site_name: systemxrs's Blog
theme:
  name: "material"
  language: zh
  features:
    - navigation.instant

markdown_extensions:
  - nl2br
  - footnotes
  - meta
  - admonition
  - pymdownx.details
  - pymdownx.superfences

plugins:
  - search
  - callouts
  - git-revision-date

copyright: 'Copyleft. All wrongs reversed.'


