site_name: systemxrs's Blog
theme:
  name: "material"
  language: zh
  features:
    - navigation.instant

# nav:
#     - Home: index.md
#     - About: about.md

# markdown_extensions:
#   - footnotes
#   - meta

# plugins:
#   - search
#   - git-revision-date

# copyright: 'Copyleft. All wrongs reversed.<br/><a href="https://beian.miit.gov.cn">冀ICP备2021025718号</a> | <a href="http://www.beian.gov.cn/">川公安网备51012202001103号</a>'


